[tool.poetry]
name = "colorful-test"
version = "0.0.4"
description = ""
authors = ["nqabenhle <nqmlabajhb024@student.wethinkcode.co.za>"]
readme = "README.md"
packages = [{include = "colorful_test"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
