[tool.poetry]
name = "leveelogic"
version = "0.8.22"
description = ""
authors = ["Rob van Putten <breinbaasnl@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pydantic = ">=1.10.7"
simplejson = "^3.19.2"
pytest = "^8.2.2"
pandas = "^2.2.2"
matplotlib = "^3.8.3"
pyproj = "^3.6.1"
requests = "^2.32.3"
xmltodict = "^0.13.0"
d-geolib = "2.4.2"
haversine = "^2.8.1"
pyshp = "^2.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
