[tool.poetry]
name = "glide_sdk"
version = "1.0.3"
description = "Python SDK for Glide Identity API"
authors = ["Stav Blyman <stavblyman@glideapi.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
pyjwt = "^2.8.0"
python-dotenv = "^1.0.1"
httpx = "^0.26.0"
pydantic = "^2.5.0"
aiohttp = "^3.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
