[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pandas-ta-remake"
version = "1.0.4"
dependencies = [
    "numpy==2.2.1",
    "pandas==2.2.3",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.2",
    "six==1.17.0",
    "tzdata==2024.2",
    "setuptools"
]
requires-python = ">= 3.11"

description = "Technical Analysis Indicators - Pandas TA is an easy to use Python 3 Pandas Extension with 150+ Indicators"
readme = "README.md"
license = {file = "LICENSE"}


[project.urls]
Repository = "https://github.com/osama-dev-repo/pandas-ta"
