[project]
name = "clipreplace"
version = "0.1.5"
authors = [{ name = "Vu Bao Long" }]
description = "Replace a section of text in a file with clipboard content."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = ["pyperclip>=1.9.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
clipreplace = "clipreplace.__main__:main"

[project.urls]
Homepage = "https://github.com/l-lumin/clipreplace"
Issues = "https://github.com/l-lumin/clipreplace/issues"

[dependency-groups]
dev = ["pytest>=8.3.4", "pytest-mock>=3.14.0"]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
testpaths = ["tests"]
