[project]
name = "seo-check-os-version"
version = "0.3.3"
description = "Default template for PDM package"
authors = [
    { name = "<wminhyuk>", email = "<seoseo1998@gmail.com>" },
]
dependencies = [
    "stundrg-check-os-ver==0.2.3",
    "check-os-ver>=0.2.1",
    "hj-check-os-version==0.2.1",
    "jacob-os-version-check==0.2.4",
    "lucas-check-os-ver==0.2.0",
    "cho-check-os-ver==0.2.3",
    "nunininu-check-os-ver>=0.3.0",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/wminhyuk/seo-check-os-version"
Issues = "https://github.com/wminhyuk/seo-check-os-version/issues"

[project.scripts]
seo-hi = "seo_check_os_version.hi:hi"
seo-random = "seo_check_os_version.hi:random_match"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
