[build-system]
requires = ["setuptools>=63", "wheel"]
build-backend = "setuptools.build_meta"



[project]
name = "sunback"
version = "0.6.16"
description = "Sets your desktop background to the most recent images of the Sun."
readme = "README.md"
license = { text = "BSD-3-Clause" }
authors = [
    { name = "C. R. Gilly", email = "chris.gilly@colorado.edu" }
]
urls = { "Homepage" = "https://github.com/GillySpace27/sunback" }
requires-python = ">=3.0"

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Science/Research",
  "Topic :: Desktop Environment",
  "Topic :: Desktop Environment :: Screen Savers",
  "Topic :: Multimedia :: Graphics :: Viewers",
  "License :: OSI Approved :: BSD License",
  "Programming Language :: Python :: 3 :: Only",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX",
  "Operating System :: MacOS",
]

dependencies = [
        "boto3",
        "matplotlib",
        "sunpy",
        "astropy",
        "scipy",
        "opencv-python",
        "xarray",
        "requests",
        ]

[project.optional-dependencies]
test = ["pytest", "pytest-runner"]

"server"= [
        "twine",
        "pillow",
        "appscript;platform_system=='Darwin'",
        "moviepy",
        "parfive",
        "beautifulsoup4",
        "html5lib",
        "numpy",
        "sunkit-image",
        "aiapy",
    ]

[project.scripts]
sunback-run = "sunback.run.run_client_background:run_client"
sunback-serve = "sunback.run.run_server_lingon:run_server_lingon"


[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"*" = ["*"]