[project]
name = "cho-check-os-ver"
version = "0.2.1"
description = "Default template for PDM package"
authors = [
    { name = "cho6019", email = "j01040864205@gmail.com" },
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/cho6019/cho-check-os-ver"
Issues = "https://github.com/cho6019/cho-check-os-ver/issues"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
