[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rollplayerlib"
version = "0.5.11.0.0.0.0.0.0.0.0.0.0.0.1"
license = { text = "MIT" }
authors = [{ name = "whirlingstars", email = "infernity@infernity.dev" }]
keywords = ["DICE", "ROLL", "RANDOM"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
description = "A library to roll dice in a simple way, but with advanced functionality."
readme = "README.md"
