[tool.poetry]
name = "django-db-utilities"
version = "0.1.5"
description = "A utility library for Django to reset databases, models, and primary keys."
authors = ["Roddy Brown <roddy@notroddy.io>"]
license = "MIT"
homepage = "https://github.com/notroddy/django-db-utilities"
repository = "https://github.com/notroddy/django-db-utilities"

[tool.poetry.dependencies]
python = ">=3.8,<3.13"  # Allowing Python versions 3.8 to 3.12
django = ">=3.2,<6.0"
questionary = "^2.1.0"
pytest = "^8.3.4"
pytest-django = "^4.9.0"

[tool.poetry.dev-dependencies]
pytest = "^8.3.4"

[tool.poetry.group.dev.dependencies]
twine = "^6.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
