[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/universal_parser_it_stud_io"]

[project]
name = "universal_parser_it_stud_io"
version = "0.0.6"
authors = [
  { name="Christian Mueller", email="christian.mueller@it-stud.io" },
]
description = "An universal parser for various file formats"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "pyyaml>=6.0.2",
  "jsonschema>=4.23.0",
  "xmlschema>=3.4.3"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/it-stud-io/universal-parser"
Issues = "https://github.com/it-stud-io/universal-parser/issues"