[project]
name = "uvmono"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Jens Peder Meldgaard", email = "JensPederM@gmail.com" }]
requires-python = ">=3.9"
dependencies = ["fire>=0.7.0", "jinja2", "pre-commit>=4.0.1", "rich>=13.9.4"]

[project.scripts]
uvmono = "uvmono:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.sdist]
include = ["src", "pyproject.toml", "README.md", "LICENSE"]
exclude = ["packages", ".docker", ".github", ".devcontainer"]

[tool.uv.workspace]
members = [
    "packages/package-a",
    "packages/package-b",
    "packages/package-c",
    "packages/package-d",
    "develop-eggs",
]

[dependency-groups]
dev = ["pytest>=8.3.4", "pytest-cov>=6.0.0"]

[tool.pytest.ini_options]
addopts = """
--cov-report=term \
--cov-report=xml:coverage.xml \
--cov=uvmono \
-ra
-vv"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
