[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gtus"
version = "0.1.1"
description = "A Python package to collect and analyze Google Trends data for US states."
readme = "README.md"
license = { file = "LICENSE.txt" }
authors = [{ name = "Levent Bulut  ", email = "levent.bulut@unt.edu" }]
dependencies = [
    "pandas>=1.3.0",
    "pytrends>=4.8.0",
    "aiohttp>=3.8.0"
]
requires-python = ">=3.7"

[tool.setuptools]
packages = ["gtus"]

[tool.setuptools.dynamic]
version = { attr = "core.__version__" }
