[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "Appcomm_python_Logger"
version = "1"
authors = [
  { name="Furkan Öztürk", email="fu.ozturk25@gmail.com" },
]
description = "A python logger similair to the lavavel logs. Made for internal use in Appcomm."
readme = "readme.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]