[tool.poetry]
name = "neso-utils"
version = "1.0.5"
description = "Library of utilities for NESO."
authors = ["Joao Nisa <joao.nisa@mesh-ai.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastavro = "1.9.1"
geopandas = "1.0.1"
numpy = "1.24.1"
randomname = "0.2.1"
rdflib = "7.1.1"
setuptools = "68.2.2"
shapely = "2.0.6"
jmxquery = "0.6.0"
requests = "2.32.3"
pyshacl = "0.29.0"

[build-system]
requires = ["poetry-core", "setuptools", "wheel", "fastavro", "geopandas", "numpy", "randomname", "rdflib", "shapely", "requests", "pyshacl"]
build-backend = "poetry.core.masonry.api"
