[project]
name = "compare_variance_residual"
version = "0.0.2"
authors = [
    { name = "Leo Schultheiss", email = "leo.schultheiss@tum.de" },
]
description = "Code for the bachelor thesis of Leo Schultheiss"
readme = "Readme.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
license = { file = "LICENSE" }
#license-files = ["LICEN[CS]E*"]
keywords = ["fMRI", "neuroimaging", "statistics", "variance partitioning"]

dependencies = [
    "requests>=2.32.3",
    "tqdm>=4.66.5",
    "transformers>=4.45.2",
    "torch>=2.5.0",
    "pandas>=2.2.3",
    "numpy>=2.1.2",
    "tables>=3.10.1",
    "scipy>=1.14.1",
    "h5py>=3.12.1",
    "ridge-utils>=0.2.0",
    "gitpython>=3.1.43",
    "himalaya>=0.4.6",
    "scikit-learn>=1.5.2",
    "matplotlib>=3.9.2",
    "voxelwise-tutorials>=0.1.7",
    "stacking-fmri>=0.1.1",
]

[project.urls]
Homepage = "https://github.com/leo-schultheiss/compare_variance_residual/tree/master"
Issues = "https://github.com/leo-schultheiss/compare_variance_residual/issues"

[tool.setuptools]
packages = ["compare_variance_residual"]