[tool.poetry]
name = "lionel"
version = "0.1.1"
description = "Predict fantasy player points and optimise the team"
authors = ["jth500 <jtobyh@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jth500/lionel"  # Optional
repository = "https://github.com/jth500/lionel"


[tool.poetry.dependencies]
python = "^3.11"
numpy = "*"
pandas = "*"
pymc = "^5.0"
pymc-marketing = ">=0.9.0"
arviz = "==0.19.0"
seaborn = "*"
pulp = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
