[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
authors = ["Emmanule Nicolle <emmanuel.nicolle@mydh.io>"]
name = "fast2app"
version = "1.2.2"
description = """A simple tool designed to automatically generate usable types, functions, and \
other useful server-side code from a list of [FastAPI](https://fastapi.tiangolo.com/) application to \
a given framework."""
readme = "README.md"
packages = [{ include = "fast2app", from = "source" }]
include = ["source/**/*.ts", "source/**/*.toml"]

keywords = [
    "fastapi",
    "nuxt",
    "composable",
    "api",
    "generation",
    "typescript",
    "framework",
    "backend",
    "frontend",
]

[tool.poetry.dependencies]
python = ">=3.11"
pydantic = "*"
fastapi = "*"
pydantic-to-typescript2 = "*"
jinja2 = "*"
camel_converter = "*"
regex = "*"
astroid = "*"
toml = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"


[tool.poetry.scripts]
fast2nuxt = "fast2app.command_line.fast2nuxt:main"

[tool.poetry.urls]
"Homepage" = "https://git.mydh.io/shared/fast2app"
"Nuxt Documentation" = "https://git.mydh.io/shared/fast2app/-/blob/development/NUXT_DOCUMENTATION.md"
"Help Desk" = "https://helpdesk.mydh.io/issue-form"
"Contact and contribution" = "https://helpdesk.mydh.io/contact-form"
"Bug Tracker" = "https://git.mydh.io/shared/fast2app/-/issues/?sort=priority&state=opened&label_name%5B%5D=bug&first_page_size=20"
