[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "probabilistic_piping/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["probabilistic_piping"]

[project]
name = "probabilistic_piping"
version = "0.0.4"
description = "Python package for probabilistic piping calculations"
readme = "README.md"
license = {text = "GNU-GPL V3"}
authors = [
  { name = "Guy Dupuits"},
  { name = "Robin Nicolai"},
  { name = "Joost Pol"},
  { name = "David Haasnoot"},
]

dependencies = [
  "numpy",
  "pandas",
  "openturns>=1.23",
  "tqdm",
]

[project.urls]
Documentation = "https://hkv-products-services.github.io/probabilistic_piping"
Source = "https://github.com/HKV-products-services/probabilistic_piping"
