[project]
name = "hj-check-os-version"
version = "0.2.0"
description = "Default template for PDM package"
authors = [
    { name = "heejin131", email = "journeyjean131@gmail.com" },
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/heejin131/hhj-check-os-version"
Issues = "https://github.com/heejin131/hj-check-os-version/issues"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
