[tool.poetry]
name = "maimai-py"
version = "0.6.0"
description = "The definitive python wrapper for MaimaiCN."
authors = ["Usagi no Niku <chenbohan911@163.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "maimai_py"}]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.28.0"
beautifulsoup4 = "^4.12.3"
cryptography = ">=38.0"
maimai-ffi = "^0.3.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-asyncio = "^0.23.0"
mitmproxy = "9.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
