[tool.poetry]
version = "1.0.1"
name = "noaa_weather_hourly"
description = "Cleans historical LCD weather files from NOAA and returns an hourly .CSV file"
authors = ["Matt Chmielewski"]
readme = "README.md"
license = "Apache-2.0"
keywords = ["noaa", "baseline-model", "sunrise-times", "noaa weather",  "8760", "energy model calibration", "sunset-times", 	"weather normalization",  "historical weather data", "weather files", "hourly weather"]
classifiers = ["Programming Language :: Python"]
packages = [
    { include = "noaa_weather_hourly" },
    { include = "noaa_weather_hourly/data" },
]

[project.urls]
homepage = "https://github.com/emskiphoto/noaa_weather_hourly"
repository = "https://github.com/emskiphoto/noaa_weather_hourly"

[project.entry-points]
noaa_weather_hourly = "noaa_weather_hourly.__main__:__main__"

[tool.poetry.scripts]
noaa_weather_hourly = "noaa_weather_hourly.__main__:__main__"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
pandas = ">1.3.5,<=2.1.4"
numpy= "<=1.26.4,>1.14.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
