[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "django-cookie-consent-compliance"
version = "0.0.1"
authors = [
  { name="Manan Bhavsar", email="mananbh9@icloud.com" },
]
description = "A deterministic package allowing user consent implication for setting cookie on django projects"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pydevmans/django-cookieconsent"
Issues = "https://github.com/pydevmans/django-cookieconsent/issues"