[project]
name = "balekit"
version = "0.0.2"
authors = [
  { name="Mohammad Parsa Mortazavi", email="mohammadparsa9053@gmail.com" },
]
description = "A tool for developing bots in Bale messenger!"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/mpmms/balekit"
Issues = "https://github.com/mpmms/balekit/issues"