[project]
name = "surrealdb-rpc"
version = "0.1.3"
authors = [{ name = "Manuel Schaaf" }]
description = "A Python library for interacting with SurrealDB via RPC."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "msgpack>=1.1.0",
    "requests>=2.32.3",
    "ulid>=1.1",
    "uuid7>=0.1.0",
    "websockets>=14.1",
]

[project.urls]
Homepage = "https://github.com/manu-schaaf/surrealdb-rpc.py"
Issues = "https://github.com/manu-schaaf/surrealdb-rpc.py/issues"

[dependency-groups]
dev = ["ipykernel>=6.29.5", "pytest>=8.3.4", "python-lsp-server[all]>=1.12.0"]
