[project]
authors = [
    { name = "sarim2000", email = "sarimbleedblue@gmail.com" },
]
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.10.4",
    "typing-extensions>=4.8.0",
    "requests>=2.32.3",
    "pytest-cov>=6.0.0",
]
description = "Python SDK for Mira Network API"
name = "mira-network"
readme = "README.md"
requires-python = "==3.10.*"
version = "0.1.5"

[project.license]
text = "MIT"

[build-system]
build-backend = "pdm.backend"
requires = [
    "pdm-backend",
]

[tool.pdm]
distribution = true

[dependency-groups]
test = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.0",
    "pytest-cov>=6.0.0",
]
