[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bsb"
description = "Black-box component framework for multiscale neural modeling"
authors = [{ name = "Robin De Schepper" }]
maintainers = [{ name = "Dimitri Rodarie", email = "dimitri.rodarie@unipv.it" }]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
requires-python = ">=3.9"
version = "4.4.0"
dependencies = [
    "bsb-core~=5.0.2",
    "bsb-json~=4.2.2",
    "bsb-yaml~=4.2.2",
    "bsb-hdf5~=5.0.2"
]

[project.optional-dependencies]
parallel = ["bsb-core[parallel]"]
neuron = ["bsb-neuron~=4.2.2"]
nest = ["bsb-nest~=4.4.0"]
arbor = ["bsb-arbor~=4.1.1"]

[project.urls]
Home = "https://github.com/dbbs-lab/bsb"
Documentation = "https://bsb.readthedocs.io/"
"Bug Tracker" = "https://github.com/dbbs-lab/bsb/issues/"
"Source Code" = "https://github.com/dbbs-lab/bsb/"

[tool.setuptools]
packages = []
[tool.bumpversion]
current_version = "4.4.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "docs: bump version: {current_version} → {new_version} [skip ci]"
commit_args = "--no-verify"

[tool.bumpversion.parts.pre_l]
values = ["dev", "a", "b", "rc", "final"]
optional_value = "final"

[[tool.bumpversion.files]]
filename = "codemeta.json"

[[tool.bumpversion.files]]
filename = "codemeta.json"
search = '"dateModified": "\d{{4}}-\d{{2}}-\d{{2}}"'
replace = '"dateModified": "{now:%Y-%m-%d}"'
regex = true
