




[project]
name = "manjpfb"
version = "0.0.9"
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.8"',
]

requires-python = '>=3.9, <=4.0' 

authors     = [{name = 'MikeTurkey', email = 'voice@miketurkey.com'}]
maintainers = [{name = 'MikeTurkey', email = 'voice@miketurkey.com'}]

description = 'FreeBSD Japanese-man Pager'
readme      = {file = "README.rst", content-type = "text/x-rst"}
license     = {file = "LICENSE"}

classifiers = [
	      'Topic :: Documentation',
	      'Topic :: Education',
	      'Topic :: Software Development :: Documentation',
	      'Development Status :: 3 - Alpha',
	      'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
	      'Operating System :: MacOS :: MacOS X',
	      'Operating System :: POSIX :: BSD :: FreeBSD',
	      'Programming Language :: Python :: 3 :: Only',
	      'Programming Language :: Python :: 3.9',
	      'Programming Language :: Python :: 3.10',
	      'Programming Language :: Python :: 3.11']



[project.urls]
Homepage = "https://miketurkey.com"
Repository = "https://github.com/MikeTurkey/manjpfb"






[project.scripts]
manjpfb = "manjpfb:main_manjpfb"